server:
  port: 9000
spring:
  application:
    name: kcloud-service-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
management:
  security:
    enabled: false